### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by ramziB99** [vChavezB/ModbusMaster_FH#5]
Hello, 
Im sorry to open an issue here but I need to contact you. I saw that in an issue opened in bastibl/gr-ieee802-11 on 2019 and you wanted to do the same thing as I am. I have an SDR ( LimeSDR USB) and I want to have the signal strength from the packets that I will captured with while moving the SDR. Did you succeed to do it ? if so I would like to know how.

Best, 
Ramzi

**Comment by vChavezB** [comment]
Sorry for the late reply, you could have mentioned me in the issue https://github.com/bastibl/gr-ieee802-11/issues/195 as I think thats the reason I did not see your message until today.

I did not explorer further solutions so I dont have any tips, sorry.
